### ISSUE TITLE
[feat] 시연전 최종 수정

### ISSUE THREAD

**Issue by l2zh** [DGU-SE-HOW-TODO/HowDroid#43]
## 📝 todo

- [x] 회원가입 아이디 에러메시지 겹치는거 수정
- [x] 실패태그 달기 뷰 겹치는거 수정
- [x] 홈 fetch시 최상단으로 스크롤
- [x] 대분류 추가 후 입력창 invisible
