### ISSUE TITLE
[ui] 홈 뷰 구현

### ISSUE THREAD

**Issue by l2zh** [DGU-SE-HOW-TODO/HowDroid#8]
## ❗ 이슈 요약

홈을 만들어볼거에요

## 📝 todo

- [x] 주차별 캘린더 구현
- [x] 대분류 추가 구현
- [x] todo 리스트 구현
- [x] todo_detail 바텀시트 구현
